### ISSUE TITLE
Service Discovery / Advanced Subscriptions

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#157]
The Subscriptions as is are basically taken straight from FubuTransportation, and they require a requesting subscriber to "know" where the source of the messages are and to be responsible for initiating contact. I don't think we'd ever want to eliminate that model, but we want an alternative where new services can just say "I'm interested in these types of event messages regardless of where they come from." This pretty well mandates some kind of centralized subscription storage, with Consul being the most likely alternative at the moment.

### Stuff that probably needs to change or be built:

* Need a way to alert all running services when the global consul subscriptions change? Maybe just sending a `SubscriptionsChanged` message to everybody on their control channel. Might require changes to the node discovery mechanisms 
* Use natural keys to describe subscriptions so it's easier to clean up or eliminate subscription storage
* Really need a UI to edit the subscription lists, even if this is only in development
* An ability to express subscriptions to certain messages without any regard for the source
* Mechanism to export desired subscriptions from a system that could be used to seed the subscription storage mechanisms. Export to a file? Have some command line helpers to import that file into the subscription storage as part of deployment?
* Subscriptions would list all possible incoming channels and known content types for the message type that the receiver can handle

### New subscription registration API:

```
// All of this is from within JasperRegistry
// In all cases, you would be able to explicitly define the incoming channel w/ the ReceiveAt() command

// Subscribe to a specific event type without regard for where the source is
Subscribe.Globally.To<Event1>();

// Subscribe to known messages matching this filter from any source
Subscribe.Globally.To(type => type is IEvent);

// Subscribe at only this node to the specific messages or message criteria
Subscribe.Locally.To<Event1>().To(type => true);

// Subscribe to everything you know you can handle
Subscribe.Globally.ToAllMessages() // NSB has this functionality and it might be occasionally useful

// Subscribe to messages from a specific source like we do today
Subscribe
    .FromSource("jasper://someserver:1000/queue1")
    .ReceiveAt("uri") // this would be optional to control what queue you want to receive at
    .ReceiveOnControlChannel() // or as an option to the line above
    .To<Event1>()
    .To(t => t is IEvent) // or by filter
```

**Comment by mike-schenk** [comment]
I'm a newbie at Jasper and completely unfamiliar with FubuTransportation, so I might be misunderstanding some things here... but I'll comment anyway.

Mostly I agree, but I think it can be simplified.

The proposal implies that multiple services could potentially be publishing the same event. I don't think that's a good pattern to encourage. Separate services, essentially by definition, should have separate responsibilities and if they have separate responsibilities, they should be producing different kinds of notifications (events).

I think the complexity of managing subscriptions in an environment with multiple producers and consumers of the same event type would outweigh the complexity of dealing with the (probably very few) situations where a service needs to subscribe to "the same" event from multiple services.

But having said that, a service that wants to subscribe to events shouldn't need to know the address of the service that is publishing them; message routing is one of the core responsibilities of a service bus. If every service is the "owner" of its own message types (event, request, and response message types), then routing a subscription message for an event type is like routing a request: it has one destination determined strictly by the type of the event.

If there really is a situation where events from multiple producers should be consumed like a single event stream, it could easily be modeled with an aggregation service. The aggregation service could receive commands from the multiple services and broadcast corresponding events to its own subscribers. This basically mimics a fan-out Exchange in RabbitMQ.

We shouldn't need any kind of broadcast "subscriptions changed" message. Each service should receive its own subscription requests and store them in its private subscription storage or a private "namespace" in a centralized subscription storage. And subscriptions don't need to list their incoming channels because there's only one: the service that publishes events of the subscribed types. I don't think there should be a .FromSource() on a subscription; rather, the bus should use the event type of the subscription to look up the address of the service responsible for that event.

To be clear, I'm not talking about multiple _instances_ of a single service. Those instances should be considered as a single logical service. In that situation, the multiple instances just need to share their subscription storage and a subscription request should be routed to any instance.

**Comment by jeremydmiller** [comment]
@mike-schenk I wasn't suggesting that multiple systems would necessarily publish the same events. The `SubscriptionsChanged` workflow you described is pretty well exactly what Jasper or Fubu3 does today between nodes of the same service, just that we don't use RabbitMQ to do that so we had to code that ourselves. The change here is trying to remove the need to specify a source by using something like consul as an enterprise wide service registry.

**Comment by jeremydmiller** [comment]
Ended up going off in a little bit different direction. Using this as a broader TODO list encompassing #122 and #168 as well.

### General Tasks

- [ ] Honor `BusSettings.DisableAllTransports`
- [ ] Pull out a new `TransportActivator` out of `ServiceBusFeature` to get that simplified
- [ ] Set `JasperRuntime.ServiceCapabilities` in bootstrapping
- [ ] Validate that there is a handler for each message that is a subscription
- [ ] Use Uri lookups in the subscription configuration
- [ ] Delete the old subscription support code
- [ ] New `ISubscriptionRepository` based on new needs
- [ ] `MessageRouter` uses the new `ISubscriptionRepository`
- [ ] Test Consul storage
- [ ] Test Marten storage
- [ ] End to end test w/ messaging between two apps that use subscriptions to do the routing
- [ ] `new PublishedMessage(Type messageType, SerializationGraph)` to help w/ what's below
- [ ] `NewSubscription.TryToDetermineRoute(PublishedMessage)`
- [ ] Use the method above for `MessageRouter`
- [ ] Deal w/ #168 in `MessageRouter` by using the first *not* `application/json` content type
- [ ] Switch over the existing Subscriptions Storyteller specs to the new model

### Published Messages
- [ ] `[Publishes]` marker attribute on concrete types gets into the capabilities
- [ ] `JasperRegistry.Publishing.Message(type)`
- [ ] `JasperRegistry.Publishing.MessagesMatching(Func<Type, bool>)`

### Service Capability Generation
- [ ] Validate and throw exceptions if a non-supported transport is referenced
- [ ] Matches published messages with content types
- [ ] Matches subscriptions to content types
- [ ] Subscription to a default receiver Uri
- [ ] Subscription to a designated receiver Uri
- [ ] Validate and throw exception if no designated Uri
- [ ] Subscribe to all supported messages
- [ ] Subscribe to all message types in `HandlerGraph` matching a filter
- [ ] Find errors related to non-supported transports
- [ ] Find errors related to subscription to a message w/ no handler chain



### Service Capability Validation
- [ ] Determine valid message routes
- [ ] Find subscriptions with no matching publisher
- [ ] Find published events with no matching subscriptions
- [ ] Find mismatched publisher/subscribers because of transport differences
- [ ] Find mismatched publisher/subscribers because of content type mismatches
- [ ] Find mismatched publisher/subscribers on both
- [ ] Unit tests against `PublisherSubscriberMismatch`
