### ISSUE TITLE
SSL support in TCP Transport

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#184]
Thinking JWT's through the message headers.

@joemcbride Any thoughts about this one?

**Comment by mike-schenk** [comment]
But how would you keep the JWTs private? An intercepted token could be used to send arbitrary messages impersonating the original sender. I'm assuming that because the built-in transports need to be backward compatible, we can't just switch to a TLS connection instead of plain TCP.

Message authentication is typically done with an HMAC, but that requires the sender and receiver to share a secret key.

I think a digital signature of the message itself is the way to go... like the RSASHA256 algorithm of JWT.

**Comment by jeremydmiller** [comment]
I don't think we have to take other options off the table. I don't *want* to get into fubu3, but it's not the end of the world. Can always make the authentication and/or actual socket manipulation be pluggable to some degree. This honestly isn't an area where I have any experience.

**Comment by joemcbride** [comment]
Agreed, doing a digital signature is probably the most secure way to send it.  I think we could potentially add a signature and keep the message format backwards compatible.  So it would be signed but the receiver would still be able to read it. We could then add in the security check to each of the systems.  Note that we would need to have some other pattern for desktop clients as those wouldn’t be able to sign the message directly.

**Comment by jeremydmiller** [comment]
I think we just use an SslStream on the sockets if the sockets are secured. For the HTTP transport, it's just using any kind of ASP.Net authentication middleware, so maybe we completely side step having to build anything there

**Comment by jeremydmiller** [comment]
Got a curve ball on this one today. Another option may be to encrypt traffic over the TCP or HTTP traffic

**Comment by jeremydmiller** [comment]
Renamed today to limit this to the TCP transport

**Comment by jeremydmiller** [comment]
I'm going to shut this down today. If you want this level of security, I say that you switch to Rabbit or some other grown up mechanism. Again, fitting with the theme that the TCP transport is mostly for prototyping and testing
