### ISSUE TITLE
Marten backed persistent messaging

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#204]
For the durable transport, let's have an implementation of `IPersistence` that is backed by a database. I'm leaning toward doing Postgres first, then Sql Server after the pattern works. It's a little more challenging than the lmdb-backed persistence just because the storage will be shared, and we'll have to get into distributed locks (advisory locks again?)

**Comment by mike-schenk** [comment]
Currently, messages are pushed into the the QueueReceiver's ActionBlock input queue as soon as they arrive. I'd like to change QueueReceiver so that it is _pulling_ messages when it has available capacity. This way, we won't end up with one node holding locks/reservations on lots of queued messages while they just sit in an in-memory queue.

For the Rhino/Fubu compatible TCP transport, I'll have the ListeningAgent/WireProtocol store the messages in a BufferBlock. Then the QueueReceiver will pull from that when it has capacity.

I'm thinking of introducing an interface like IQueueReader with two async methods: `Task<Envelope> PeekLock()` and `Task Receive(Envelope env)`. PeekLock will return a task that completes after an envelope is available and an exclusive lock has been taken on it. Receive will permanently remove the envelope, releasing the lock. I'll probably end up with more methods on that interface to deal with failure or retry.

This pull model instead of the push model will also make it possible to add support for external queues like Azure SB, RabbitMQ, Kafka, MSMQ, etc.

**Comment by jeremydmiller** [comment]
I like that idea for the durable transports, but would you do that for the fire and forget transport as well, or just keep what's there? Are you thinking that you'd have some kind of distributed lock across nodes to be the one single sender? We'll probably have other usages for that functionality down the line anyway. Consul has some support for that out of the box, and we could also support advisory locks thru either Postgres or Sql Server.

I think this would make the circuit breaker functionality easier.

**Comment by mike-schenk** [comment]
For the sake of code re-use I'll do it for both the Durable and Lightweight transports since a bunch of this ends up in TransportBase anyway.

As for sending outgoing messages, I hadn't thought about the circuit breaker before today, so I was thinking of letting nodes send their own outgoing messages until they run out, then they could go look in the database for any that have been left behind by other nodes that might have gone down.

**Comment by jeremydmiller** [comment]
There's nothing that says we have to keep TransportBase if that's getting in the way. The push model might make more sense for the fire & forget. Could just push the methods in TransportBase all down, then replace w/ a pull model in the durable.

**Comment by jeremydmiller** [comment]
Saying this is strictly Marten now. We'll open new issues for Sql Server later

**Comment by jeremydmiller** [comment]
So, it's *code complete* & basic unit & integration test done. There are smaller issues for various bits and pieces that would make it more robust, and the giant story about durability testing. I'm actually going to close this.

**Comment by ShaneCourtrille** [comment]
FYI documentation here https://jasperfx.github.io/documentation/messaging/transports/durable/ still links to this.
