### ISSUE TITLE
Support for correlation/causation pattern

### ISSUE THREAD

**Issue by tjaskula** [JasperFx/jasper#299]
Correlation/causation pattern is pretty useful in message driven architectures to track all the messages that has been produced during a business transaction. We're using this pattern in our CQRS/EventSourced scenario to track commands and events. 

We have the following triplet: **messageId** (unique for every message), **correlationId**: should be common for all messages in the same business transaction, **causationId**: should contain the messageId of the message that originated this message. We store those in message enveloppe/metadata.

Assuming all messaging is done via Jasper. We were looking for passing causationId, correlationId and messageId from commands to events. Meaning that when command is received it would already have an enveloppe (set for example by a middleware), then a command handler is called invoking behavior on aggregate which will produce events, ideally when publishing events we would like to post it with enveloppe/metadata where the event causationid = command messageId and both would have the same correlationId. The point is that we would like to avoid manual recopy those from command enveloppe to event enveloppe. It would be nice to plug some code in somewhere in the middle to do it in generic way for all.

If I have events as E and command as C this would give the following scenario:

Message type | Message Id | CorrelationId | CausationId | Comment
---------------|------------|--------------|--------------|----------
E1 | 5 | 17 | - | this is the first input to our system so no causationId
C1 | 6 | 17 | 5  | this was caused by event 5
E1 | 7 | 17 | 6  | this was caused by command 6

**Comment by jeremydmiller** [comment]
Incorporate this? https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md

**Comment by tjaskula** [comment]
I didn't know there was a protocol for that. It seems that what you linked is more related to HTTP request tracing while my point was more related to messaging (either commands or events, or other message types). It is something like this http://masstransittemp.readthedocs.io/en/latest/usage/messages.html#correlating-messages

**Comment by jeremydmiller** [comment]
@tjaskula This is a little embarrassing how long it's taken me to get back to this.

As of now (I might have changed some properties, but they were already there in one form or another),  we have:

Envelope.ParentId == "CausationId"
Envelope.Id == "Message Id"

and it's specialized to saga usages, but "SagaId" is roughly analogous to CorrelationId.

Also, Jasper tracks "OriginalId", which is the message id that kicked off the whole workflow. Since that's really a duplication to otehr items, I might delete that completely.

I'm going to think through maybe:
* Renaming "Id" to "MessageId".
* Renaming "ParentId" to "CausationId"
* Adding a new `CorrelationId` and surfacing that through some kind of new API. 


And all new docs explaining all this 'cause it's worthless otherwise.

**Comment by jeremydmiller** [comment]
Alright, here's the plan:

- [ ] Rename `Envelope.Id` to `Envelope.MessageId`, but leave the header name alone
- [ ] Rename `Envelope.ParentId` to `Envelope.CausationId` and change the header name
- [ ] Rename `Envelope.OriginalId` to `Envelope.CorrelationId`

## Correlation Id Logic
- [ ] Set by `MessageContext.CorrelationId`, which is either the original Envelope.CorrelationId or a new Guid. *Later on, we'll have a way of capturing this in HTTP requests maybe???*
- [ ] `MessageContext` sets the value on all captured `Envelope` objects
