### ISSUE TITLE
Custom Lamar Instances for IOptions and ILogger

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#480]
Just like we do for Lamar's aspnet core stuff

**Comment by MelbourneDeveloper** [comment]
@jeremydmiller Hi. Any chance we could see a sample of how to use Lamar with ILogger?

**Comment by jeremydmiller** [comment]
What do you mean? There's no difference from any other container that supports the ASP.Net registration abstractions.

This issue was meant to be a minor optimization that might have gotten removed come to think of it.

**Comment by MelbourneDeveloper** [comment]
@jeremydmiller that's not what I mean. In modern aspnet core scenarios using `IServiceCollection` registration is hidden. Most 3rd party libraries bury their registration in extension methods. For example, to register ILoggerFactory with Serilog, we have to call this:

```cs
var webHostBuilder = WebHost.CreateDefaultBuilder().UseSerilog();
```

So, we have to go digging around to find out what it's doing under the hood. But, the problem is that the implementations often have a access modifier of `internal` so accessing the constructor without using Microsoft's aspnet IoC container becomes confusing or difficult.

I'm just asking to see an example of how to instantiate something like Serilog's `ILogger` implementation or some other common library that implements `ILogger`.

**Comment by jeremydmiller** [comment]
You *can* build types with internal constructors with Lamar now, so I'm still not understanding what you're asking. The `UseSerilog()` is very likely just using the `IWebHostBuilder.ConfigureServices()` method that in turn uses `IServiceCollection`

**Comment by MelbourneDeveloper** [comment]
@jeremydmiller 

> You can build types with internal constructors with Lamar now

That's what I am asking. Is there an example of doing this somewhere?
