### ISSUE TITLE
ASP.net Core Logging Configuration is lost from Host.CreateDefaultBuilder() when UseJasper is called

### ISSUE THREAD

**Issue by TheFellow** [JasperFx/jasper#668]
Taking a completely blank "headless" Jasper hosted service loses the logging configuration settings pulled through in the default builder.

This appears to be the same exact issue as was reported in the Lamar issue [#80](https://github.com/JasperFx/lamar/issues/80)

I'm using a workaround that I found in the Lamar [tests](https://github.com/JasperFx/lamar/blob/17fd68e3ef9062040a090a3921c0e3eded1d6ad3/src/Lamar.AspNetCoreTests/integrating_with_HostBuilder.cs#L89) shown below for simplicity:

```csharp
.ConfigureServices((context, services) =>
{
    // This is needed because of https://github.com/aspnet/Logging/issues/691
    services.AddSingleton<ILoggerFactory, LoggerFactory>(sp =>
        new LoggerFactory(
            sp.GetRequiredService<IEnumerable<ILoggerProvider>>(),
            sp.GetRequiredService<IOptionsMonitor<LoggerFilterOptions>>()
        )
    );
})
```

**Questions**

1. Is this still the correct workaround?
2. Should this be done by Jasper anyway since this is a known problem?

**Comment by huesla** [comment]
I have encountered a similar issue, where .UseJasper() caused Serilog logging configuration to be cleared.
When I used
`private static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog()
                .UseJasper<JasperConfiguration>()
                ...`
it usedthe [default builder settings](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#default-builder-settings) instead of the Serilog settings.

The solution was to call UseJasper() before UseSerilog()

`private static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseJasper<JasperConfiguration>()
                .UseSerilog()

**Comment by jeremydmiller** [comment]
@huesla With the newest Oakton, this seems to be very specifically a problem with Serilog only.

**Comment by jeremydmiller** [comment]
Fixed awhile back in Lamar itself.
