### ISSUE TITLE
Hangfire backed delayed job processor

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#96]
New addon library that uses Hangfire to do the delayed job processing. Think this is what folks will most likely settle on for "robust" solutions.

**Comment by jeremydmiller** [comment]
A quick brain dump:

* Will need an implementation of `IDelayedJobProcessor` in the container. There is a specific
   method off of JasperBusRegistry you can use to do the registration that has some other bookkeeping logic (that we should probably eliminate in the long run)
* From my reading of Hangfire, we need the arguments to be something simple that is easily serialized by Newtonsoft. We might add a new method to `IHandlerPipeline` or something all new with the signature like `Invoke(byte[] data, Dictionary<string, string>)`, and have that construct an Envelope and go
* Might want to use #99 under the covers because that would let you delegate to the in memory queue's built in retries queue and error handling mechanisms

**Comment by mwuthrich** [comment]
Thoughts on Hangfire so far:
* To which specific method on JasperBuRegistry are you referring?
* We need to tell Hangfire about our DI so that it can construct what it needs to process the job.  Are we sticking with Structuremap?
* Hangfire comes with support for MSSQL, MSMQ, and Redis out of the box.  There are plugins for in-memory and a few others.  The downside with database persistence is that it polls on an interval (15s by default).  
* It might be nice to have a default persistence method that doesn't require setting up a database or external queue.  Maybe we can write an LMDB persistence plugin?  Or will the default just be in memory?
* Not all of the methods on IDelayedJobProcessor can be implemented with Hangfire because it doesn't really give any visibility or control over items once they are added to the queue.  I think the only applicable method is Enqueue.

**Comment by jeremydmiller** [comment]
@mwuthrich I think I want to just shut this one down. I don't want to back off of the auditing/instrumentation, and I've done enough research to see how to do a database backed version of this without *too* much risk. I closed the Lmdb backed version of this just because I really don't want to have to do it or support it after we had a couple lmdb related issues in production:/
